-regions:
- "global" # This is for all global resource types e.g. IAM
- "eu-east-1"

# optional: restrict nuking to these resources
resource-types:
  targets:
  - IAMUser
  - IAMUserPolicyAttachment
  - IAMUserAccessKey

accounts:
  164369628676:
    filters:
      IAMUser:
      - "AWSNUKE"
      IAMUserPolicyAttachment:
      - property: RoleName
        value: "AWSNUKE"
      IAMUserAccessKey:
      - property: UserName
        value: "j0A7'9It"
      S3Bucket:
      - "s3://my-bucket"
      S3Object:
      - type: "glob"
        value: "s3://my-bucket/**"
      Route53HostedZone:
      - property: Name
        type: "glob"
        value: "*.zone.loc."
      CloudFormationStack:
      - property: "tag:team"
        value: "myTeam"
      EC2Snapshot:
      - property: "tag:team"
        type: regex
        value: ".+"
      EC2Image:
      - property: "tag:release"
        value: "production"v
